### ISSUE TITLE
What is the version of transformers and adapter-transformers?

### ISSUE THREAD

**Issue by Charity333333333** [lavine-lmu/m4Adapter#2]
What is the version of transformers and adapter-transformers?
These two packages were significantly updated in subsequent upgrades, making your code unusable. 
Thank you, I really need it.

**Comment by wenlai-lavine** [comment]
Hi, thanks for your interest in our paper. Unfortunately, the python environment used in this work has deleted, I am not able to check the version of transformers and adapter-transformers.

Based on the time period of this work, you can try to reduce the version of transformers to `4.18.0`. adapter-transformer to `3.0.0`. or, based on the [code](https://github.com/wenlai-lavine/m4Adapter/blob/main/adapters/m2m.py) I provided, you can easily implement the adapter in m2m_100 by changing the code of the version you are working with yourself.

**Comment by Charity333333333** [comment]
How do you solve this problem: can't start new thread

`Process Process-185:
Traceback (most recent call last):
  File "/home/xianyt/xjl/anaconda3/envs/m4a/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/xianyt/xjl/anaconda3/envs/m4a/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xianyt/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 316, in _worker_loop
    data_queue.put((idx, data))
  File "/home/xianyt/xjl/anaconda3/envs/m4a/lib/python3.8/multiprocessing/queues.py", line 88, in put
    self._start_thread()
  File "/home/xianyt/xjl/anaconda3/envs/m4a/lib/python3.8/multiprocessing/queues.py", line 173, in _start_thread
    self._thread.start()
  File "/home/xianyt/xjl/anaconda3/envs/m4a/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x2b5f91918310>`

**Comment by Charity333333333** [comment]
thank you
